# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2d299d3e96e7efa33059b644d798e739"
name = "wishlist-inspire"
handle = "wishlist-inspire-212"
application_url = "https://glad-exec-fantasy-pure.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "esmatullahmohammadi.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://glad-exec-fantasy-pure.trycloudflare.com/auth/callback",
  "https://glad-exec-fantasy-pure.trycloudflare.com/auth/shopify/callback",
  "https://glad-exec-fantasy-pure.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
